//! Fixture manifest generator: measures every file in `testdata/fixtures/`
//! with the engine's own decoder and writes `testdata/fixtures.toml`.
//!
//! Split from [`decode_fixture_smoke`](../decode_fixture_smoke.rs) on purpose.
//! The smoke test is a *gate* and must stay cheap and read-only; regenerating
//! the ground truth is a maintenance action that runs only when the corpus
//! changes. Keeping them apart also means the smoke test can never silently
//! rewrite the expectations it is checking against.
//!
//! Ignored by default — `scripts/make_fixtures.sh` invokes it explicitly with
//! `--ignored`.
//!
//! # Why the expectations come from the engine
//!
//! It is tempting to hand-write "expected RMS ≈ -5.0 dBFS" into the manifest.
//! That number is a function of the encoder's default settings, the GStreamer
//! version, and the source material — all of which change without anyone
//! editing the repository. Measuring instead means the manifest is a
//! *recorded observation* of a known-good build, so a later run that decodes
//! the same bytes differently is a real signal, not encoder noise.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

/// One fixture's measured properties.
struct Measured {
    path: String,
    sample_rate: u32,
    channels: usize,
    frames: u64,
    peak: f64,
    rms: f64,
}

/// Decode `path` to exhaustion and measure it.
///
/// Lossy codecs legitimately decode to a different number of frames than the
/// encoder was given (encoder delay, padding, gapless metadata), so `frames`
/// is recorded as observed rather than predicted. Duration assertions in the
/// smoke test are therefore tolerant, while rate and channel count — which no
/// codec may change — are exact.
fn measure(path: &Path) -> Result<Measured, String> {
    let mut decoder = engine::decode::Decoder::open(path).map_err(|e| e.to_string())?;

    let (sample_rate, channels) = {
        let info = decoder.info();
        (info.sample_rate, info.channels)
    };

    let mut frames = 0u64;
    let mut peak = 0.0f64;
    let mut sum_squares = 0.0f64;
    let mut samples = 0u64;

    loop {
        match decoder.decode_next(8192) {
            Ok(chunk) => {
                // Native-DSD chunks carry no interleaved PCM; nothing to measure.
                if chunk.raw_dsd.is_some() || chunk.frame_count == 0 {
                    break;
                }
                frames += chunk.frame_count as u64;
                for &s in &chunk.samples {
                    let magnitude = s.abs() as f64;
                    if magnitude > peak {
                        peak = magnitude;
                    }
                    sum_squares += magnitude * magnitude;
                    samples += 1;
                }
            }
            Err(engine::decode::DecodeError::EndOfStream) => break,
            Err(e) => return Err(format!("{e}")),
        }
    }

    if samples == 0 {
        return Err("decoded zero samples".to_string());
    }

    Ok(Measured {
        path: path
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default(),
        sample_rate,
        channels,
        frames,
        peak,
        rms: (sum_squares / samples as f64).sqrt(),
    })
}

/// Escape a TOML basic string. Fixture names are simple, but a stray quote
/// would produce a manifest that fails to parse with a confusing error.
fn toml_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("testdata/fixtures")
}

fn manifest_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("testdata/fixtures.toml")
}

#[test]
#[ignore = "regenerates testdata/fixtures.toml; run via scripts/make_fixtures.sh"]
fn write_fixture_manifest() {
    let dir = fixtures_dir();
    assert!(
        dir.is_dir(),
        "no fixture directory at {} — run scripts/make_fixtures.sh first",
        dir.display()
    );

    let mut paths: Vec<PathBuf> = std::fs::read_dir(&dir)
        .expect("read fixtures dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some())
        .collect();
    paths.sort();

    assert!(!paths.is_empty(), "{} exists but is empty", dir.display());

    let mut out = String::new();
    out.push_str(
        "# Decode fixture corpus — GENERATED by `cargo test --test decode_fixture_measure -- --ignored`.\n\
         # Do not hand-edit: `scripts/make_fixtures.sh` regenerates this file from the\n\
         # encoded corpus, and every value below is a measurement, not an expectation\n\
         # written by a human.\n\
         #\n\
         # `status = \"missing\"` entries are formats this repository has no encoder for\n\
         # (APE, TTA, DSD). They are recorded so the coverage gap stays visible in\n\
         # review; the smoke test asserts nothing about them.\n\
         #\n\
         # Frame counts are what the engine actually decoded, which for lossy codecs\n\
         # differs from the encoder input by design (encoder delay, padding, gapless\n\
         # metadata). Sample rate and channel count are exact — no codec may alter them.\n\n",
    );
    out.push_str("schema = 1\n\n");
    out.push_str("[[fixture]]\n");
    out.push_str("name = \"ape_monkey\"\nstatus = \"missing\"\nreason = \"no GStreamer encoder for Monkey's Audio; `ape-decoder` is decode-only\"\n\n");
    out.push_str("[[fixture]]\n");
    out.push_str("name = \"tta_true_audio\"\nstatus = \"missing\"\nreason = \"no GStreamer encoder for TTA; `src/decode/tta.rs` is a native decoder with no matching encoder\"\n\n");
    out.push_str("[[fixture]]\n");
    out.push_str("name = \"dsd_dsf\"\nstatus = \"missing\"\nreason = \"no GStreamer encoder for DSD; DSF/DFF decode is implemented natively with no encoder counterpart\"\n\n");

    let mut measured_count = 0usize;
    for path in &paths {
        match measure(path) {
            Ok(m) => {
                let duration = m.frames as f64 / m.sample_rate as f64;
                let _ = writeln!(out, "[[fixture]]");
                let _ = writeln!(out, "name = \"{}\"", toml_escape(&m.path));
                let _ = writeln!(out, "status = \"generated\"");
                let _ = writeln!(out, "path = \"fixtures/{}\"", toml_escape(&m.path));
                let _ = writeln!(out, "sample_rate = {}", m.sample_rate);
                let _ = writeln!(out, "channels = {}", m.channels);
                let _ = writeln!(out, "frames = {}", m.frames);
                let _ = writeln!(out, "duration_secs = {duration:.6}");
                let _ = writeln!(out, "peak = {:.8}", m.peak);
                let _ = writeln!(out, "rms = {:.8}", m.rms);
                out.push('\n');
                measured_count += 1;
            }
            Err(e) => {
                // A file the encoder produced but the engine cannot open is a
                // real defect, and must not be quietly written into the
                // manifest as if it were expected coverage.
                panic!(
                    "fixture {} could not be measured: {e}\n\
                     Either the encoder is producing something the engine cannot read, or the\n\
                     engine has lost a codec. Fix one side or the other; do not record it.",
                    path.display()
                );
            }
        }
    }

    std::fs::write(manifest_path(), out).expect("write manifest");
    eprintln!(
        "wrote {} measured fixtures to {}",
        measured_count,
        manifest_path().display()
    );
}
